### PR TITLE
Add system to support alternative target output formats

### PR DESCRIPTION
**Pull request by expectocode**
And implement JSS format.

### CODE REVIEW

**Comment by expectocode** [comment]
nit pick changes welcome, please don't hold back

**Comment by ed741** [comment]
I've made a few commits on the superPixel branch before seeing this, including updating the examples and updating the README (which doesn't yet cover superpixels so dw about that). So please pull from that branch and update the examples in ./examples/ and also add to the readme. And check that the tests still run of course.
Thanks!

**Comment by expectocode** [comment]
Some tests are failing but I think it's due to the recent FileRun changes

**Comment by ed741** [comment]
Tests Seem to work for me - i think it could be the timeout is set too short so your computer isn't fast enough to find a solution. I will extend this later.

**Pull request merged**
